# Generated by Django 5.2.8 on 2026-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('verified', 'Подтвержден'), ('expired', 'Истек')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phone Auth Code',
                'verbose_name_plural': 'Phone Auth Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'status'], name='main_interf_phone_1db743_idx')],
            },
        ),
    ]
